# Generated by Django 4.2.6 on 2023-12-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_file_name_alter_media_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mime_type',
            field=models.CharField(blank=True, choices=[('image/jpeg', 'Jpeg'), ('image/png', 'Png'), ('image/gif', 'Gif'), ('image/webp', 'Webp'), ('video/mp4', 'Mp4'), ('video/webm', 'Webm')], help_text='The mime type of the media file.', max_length=100),
        ),
    ]
