# Generated by Django 4.2.6 on 2023-12-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_type', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=50)),
                ('total_occupancy', models.IntegerField()),
                ('total_bedrooms', models.IntegerField()),
                ('total_bathrooms', models.IntegerField()),
                ('summary', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('has_tv', models.BooleanField()),
                ('has_kitchen', models.BooleanField()),
                ('has_heating', models.BooleanField()),
                ('has_internet', models.BooleanField()),
                ('price', models.IntegerField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
