# Generated by Django 4.2.6 on 2023-12-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='home_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
    ]
