# Generated by Django 4.2.6 on 2023-12-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_home_type_remove_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='home_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment')], default='House', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Entire Place', 'Entire Place'), ('Private Room', 'Private Room'), ('Shared Room', 'Shared Room')], default='Entire Place', max_length=20),
        ),
    ]
